-- SELECT
--     B1_COD,
--     B1_DESC,
--     SUM(SALDO) SALDO,
--     sum(SALDO_10) SALDO10,
--     SUM(SALDO_02) SALDO_02,
--     SUM(SALDO_11) SALDO_11,
--     SUM(COBERTURA) COBERTURA
--     FROM (
--     SELECT 
--         B.B1_COD,
--         B.B1_DESC,
--         SUM(A.B2_QATU) SALDO,
--         SUM(IIF(A.B2_LOCAL='10',A.B2_QATU,0)) SALDO_10,
--         SUM(IIF(A.B2_LOCAL='02',A.B2_QATU,0)) SALDO_02,
--         SUM(IIF(A.B2_LOCAL='11',A.B2_QATU,0)) SALDO_11,
--         ISNULL((SELECT CASE WHEN ((sum(A.B2_QATU)/SUM(C.D2_QUANT)*(10)) <10) THEN ISNULL(sum(A.B2_QATU)/SUM(C.D2_QUANT)*(10),0) END  
--     FROM  SD2010 C (NOLOCK) 
--     WHERE C.D_E_L_E_T_='' AND A.B2_FILIAL='15' AND  C.D2_LOCAL='10'  AND C.D2_COD=A.B2_COD AND CAST(D2_EMISSAO AS DATE) BETWEEN CAST(dateadd(DAY,-10,GETDATE())as date) AND CAST(D2_EMISSAO AS DATE)),0) AS COBERTURA
-- FROM SB2010 A (NOLOCK)
-- LEFT JOIN SB1010 B (NOLOCK) ON B.D_E_L_E_T_=''  AND  B.B1_COD=A.B2_COD
-- WHERE A.D_E_L_E_T_='' AND A.B2_FILIAL='15' AND A.B2_COD=B.B1_COD AND  A.B2_LOCAL IN ('10','02','11')
-- GROUP BY B.B1_COD,B.B1_DESC,A.B2_COD,A.B2_FILIAL ) AS T
-- GROUP BY T.B1_DESC,T.B1_COD
-- HAVING SUM(COBERTURA) > 0 AND (SUM(SALDO_02)>0 OR SUM(SALDO_11)>0)
-- ORDER BY B1_COD








-- SELECT
--     sum(SALDO    )SALDO       ,
--     sum(SALDO_02 )SALDO_02    ,
--     sum(SALDO_11 )SALDO_11    ,
--     sum(COBERTURA)COBERTURA
--     FROM ( SELECT 
--         B.B1_COD,
--         B.B1_DESC,
--         CASE WHEN sum(C.B2_QATU)>0 and A.D2_LOJA = '10'  THEN sum(C.B2_QATU) else 0 END SALDO,
--         CASE WHEN sum(C.B2_QATU)>0 and A.D2_LOJA ='02' THEN C.B2_QATU else 0 END SALDO_02,
--         CASE WHEN sum(C.B2_QATU)>0 and A.D2_LOJA ='11' THEN C.B2_QATU else 0 END SALDO_11,
--         CASE WHEN A.D2_LOJA = '10' and ((sum(C.B2_QATU)/SUM(A.D2_QUANT)*(10)) <=10) THEN sum(C.B2_QATU)/SUM(A.D2_QUANT)*(10) else 0 END AS COBERTURA
-- FROM SD2010 A (NOLOCK)
-- LEFT JOIN SB1010 B (NOLOCK) ON B.D_E_L_E_T_=''  AND  B.B1_COD=A.D2_COD
-- LEFT JOIN SB2010 C (NOLOCK) ON C.D_E_L_E_T_=''  AND  C.B2_COD=A.D2_COD
-- WHERE A.D_E_L_E_T_='' AND A.D2_FILIAL='15' AND  D2_LOJA IN ('10','02','11') AND A.D2_COD=B.B1_COD AND CAST(D2_EMISSAO AS DATE) BETWEEN CAST(dateadd(DAY,-10,GETDATE())as date) AND CAST(D2_EMISSAO AS DATE)
-- GROUP BY B.B1_COD,B.B1_DESC,A.D2_FILIAL,A.D2_LOJA,C.B2_QATU,A.D2_EMISSAO
-- ) AS T
-- GROUP BY T.B1_DESC,T.B1_COD, T.SALDO, T.SALDO_02,T.SALDO_11,T.COBERTURA
-- HAVING SALDO > 0 AND SALDO_02 > 0 OR SALDO_11 > 0
-- ORDER BY B1_COD




-- SELECT D2.D2_COD, D2.D2_LOJA,SUM(B2_QATU) FROM SB2010
-- INNER JOIN SD2010 D2 ON B2_COD=D2_COD AND D2.D_E_L_E_T_='' AND D2.D2_FILIAL='15' AND  D2.D2_LOJA IN ('10','02','11')
-- GROUP BY B2_QATU,D2.D2_COD,D2.D2_LOJA
-- ORDER BY D2.D2_COD



-- CASE WHEN ((sum(A.B2_QATU)/SUM(C.D2_QUANT)*(10)) <10) THEN sum(A.B2_QATU)/SUM(C.D2_QUANT)*(10) END
-- AND  D2_LOJA IN ('10','02','11')
-- AND CAST(D2_EMISSAO AS DATE) BETWEEN CAST(dateadd(DAY,-10,GETDATE())as date) AND CAST(D2_EMISSAO AS DATE)





-- UNION ALL

-- SELECT 
--     B.B1_COD,
--     B.B1_DESC,
--     SUM(C.B2_QATU) SALDO
--     FROM SD2010 A (NOLOCK)
-- INNER JOIN SB1010 B (NOLOCK) ON B.D_E_L_E_T_=''  AND  B.B1_COD=A.D2_COD
-- INNER JOIN SB2010 C (NOLOCK) ON C.D_E_L_E_T_=''  AND  B.B1_COD=C.B2_COD
-- WHERE B1_COD='000013         ' and B2_FILIAL='15' AND D2_LOJA ='10'
-- GROUP BY B.B1_COD,B.B1_DESC



-- UNION ALL 

-- SELECT 
--     B.B1_COD,
--     B.B1_DESC,
--     SUM(A.B2_QATU) SALDO,
--     CASE WHEN (SUM(A.B2_QATU) > 0) THEN SUM(A.B2_QATU) END  SALDO_02
-- FROM SB2010 A (NOLOCK)
-- FULL OUTER JOIN SB1010 B ON B.D_E_L_E_T_=''  AND  B.B1_COD=A.B2_COD
-- FULL OUTER JOIN SD2010 C ON B.D_E_L_E_T_=''  AND  B.B1_COD=A.B2_COD
-- WHERE A.D_E_L_E_T_='' AND A.B2_COD ='023695'  AND C.D2_FILIAL = '02'
--  GROUP BY B.B1_COD,B.B1_DESC,A.B2_COD,A.B2_QATU, A.B2_FILIAL



