SELECT B2_COD,
        B2_QATU,
        CASE WHEN SALDO_02 >0 THEN SALDO_02 END SALDO_02,
        CASE WHEN SALDO_11 >0 THEN SALDO_11 END SALDO_11,
        COBERTURA   FROM  
(SELECT A.B2_COD,
        A.B2_QATU,
        CASE WHEN B.D2_LOJA ='02' THEN A.B2_QATU END SALDO_02,
        CASE WHEN B.D2_LOJA ='11' THEN A.B2_QATU END SALDO_11,
        (SELECT CASE WHEN ((sum(A.B2_QATU)/SUM(C.D2_QUANT)*(10)) <10) THEN sum(A.B2_QATU)/SUM(C.D2_QUANT)*(10) END  
        FROM  SD2010 C (NOLOCK) 
        WHERE C.D_E_L_E_T_='' AND A.B2_FILIAL='15' AND  C.D2_LOJA IN ('10')  AND C.D2_COD=A.B2_COD AND CAST(D2_EMISSAO AS DATE) BETWEEN CAST(dateadd(DAY,-10,GETDATE())as date) AND CAST(D2_EMISSAO AS DATE)
        ) AS COBERTURA FROM SB2010 A (NOLOCK)
LEFT JOIN SD2010 B (NOLOCK) ON B.D_E_L_E_T_='' AND B.D2_FILIAL ='15' AND B.D2_COD=A.B2_COD AND B.D2_LOJA IN ('02','11','10')
WHERE A.D_E_L_E_T_='' AND A.B2_FILIAL ='15'
GROUP BY A.B2_QATU,B.D2_LOJA,A.B2_COD,A.B2_FILIAL ) AS QRY
GROUP BY QRY.B2_COD,QRY.B2_QATU,QRY.COBERTURA,QRY.SALDO_02,QRY.SALDO_11
HAVING QRY.B2_QATU >0 AND QRY.COBERTURA>0 AND COBERTURA < 10 AND SALDO_02 > 0 OR SALDO_11 > 0 



SELECT B2_COD, B2_QATU,D2_LOJA FROM SB2010 
INNER JOIN SD2010 ON B2_COD =D2_COD AND D2_COD='000'